[project]
name = "anand-nagar-backend"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.140.13",
    "python-dotenv>=1.2.2",
    "SQLAlchemy>=2.0.51",
    "psycopg2-binary>=2.9.12",
    "clerk-backend-api>=6.0.1",
    "svix>=1.99.1",
    "email-validator>=2.3.0",
]


[tool.fastapi]
entrypoint = "app.main:app"